[package]
name = "rustok-storefront"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
leptos = { workspace = true, features = ["ssr"] }
leptos-auth = { workspace = true }
leptos-graphql = { workspace = true }
serde = { workspace = true, features = ["derive"] }
